import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================
// 种子数据 - APPLE TRAVEL 苹果旅行
// 专注日本高端定制旅行
// ============================================

// Unsplash 图片（使用日本相关的高质量图片）
const IMG = {
  // 目的地封面
  tokyo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80',
  kyoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80',
  osaka: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80',
  hokkaido: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&q=80',
  okinawa: 'https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=1200&q=80',

  // 行程封面
  japanZen: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80',
  japanSakura: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80',
  japanOnsen: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80',

  // 故事封面
  story1: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80',
  story2: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80',
  story3: 'https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=1200&q=80',

  // 专家头像
  expert1: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
  expert2: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
  expert3: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
};

async function main() {
  console.log('开始填充种子数据...');

  // 1. 创建情感（5 种核心情感）
  const emotions = await Promise.all([
    prisma.emotion.upsert({
      where: { name: 'Contentment' },
      update: {},
      create: {
        name: 'Contentment',
        nameCn: '宁静',
        description: '在京都古寺中聆听钟声，感受内心的平静与满足',
        color: '#9b8ec4',
        
        sortOrder: 1,
        isActive: true,
      },
    }),
    prisma.emotion.upsert({
      where: { name: 'Revitalized' },
      update: {},
      create: {
        name: 'Revitalized',
        nameCn: '焕新',
        description: '在温泉乡中放松身心，重新焕发活力',
        color: '#e67e22',
        
        sortOrder: 2,
        isActive: true,
      },
    }),
    prisma.emotion.upsert({
      where: { name: 'Freedom' },
      update: {},
      create: {
        name: 'Freedom',
        nameCn: '自在',
        description: '骑着自行车穿梭在樱花树下，享受无拘无束的自由',
        color: '#3498db',
        
        sortOrder: 3,
        isActive: true,
      },
    }),
    prisma.emotion.upsert({
      where: { name: 'Distraction' },
      update: {},
      create: {
        name: 'Distraction',
        nameCn: '惊喜',
        description: '在东京街头偶遇一场樱花雨，感受意想不到的惊喜',
        color: '#e74c3c',
        
        sortOrder: 4,
        isActive: true,
      },
    }),
    prisma.emotion.upsert({
      where: { name: 'Challenged' },
      update: {},
      create: {
        name: 'Challenged',
        nameCn: '挑战',
        description: '攀登富士山，在日出时分站在山顶，感受征服的成就感',
        color: '#2c3e50',
        
        sortOrder: 5,
        isActive: true,
      },
    }),
  ]);

  console.log('✅ 情感数据已创建');

  // 2. 创建目的地（日本 7 大目的地 - AI 生成丰富数据）
  const destinations = await Promise.all([
    prisma.destination.upsert({
      where: { slug: 'tokyo' },
      update: {
        nameCn: '东京',
        description: '传统与未来交汇的世界级都市，从百年神社到摩天大楼，从米其林三星到街边拉面，东京拥有无限可能。',
        descriptionLong: '东京是一座永不停歇的城市，在这里你可以在清晨参观明治神宫感受宁静，在中午穿梭于银座的精品店，在夜晚登上东京塔俯瞰万家灯火。作为全球米其林星星最多的城市，东京是美食家的天堂；作为动漫与科技的中心，这里是二次元爱好者的圣地。无论你是第一次来日本还是资深旅行者，东京总能给你新的惊喜。\n\n东京分为 23 个特别区，每个区都有独特的魅力：新宿的繁华、涩谷的潮流、浅草的怀旧、银座的奢华、原宿的青春、秋叶原的动漫……一座城市，万种体验。',
        coverImage: IMG.tokyo,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
          'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
          'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
          'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🏯 浅草寺 — 东京最古老的寺庙，雷门大灯笼是东京的标志',
          '🗼 东京塔 & 晴空塔 — 360° 俯瞰整座城市的壮观',
          '🌸 新宿御苑 — 四季花卉，樱花季绝美',
          '🛍️ 银座 & 表参道 — 世界顶级购物天堂',
          '🍣 筑地场外市场 — 新鲜寿司与海鲜的圣地',
          '🎮 秋叶原 — 动漫、游戏、电器爱好者的天堂',
          '🎭 歌舞伎座 — 欣赏一场传统歌舞伎表演',
        ]),
        bestSeason: '春秋两季最佳（3-5 月樱花，10-11 月红叶），全年皆宜',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 1,
      },
      create: {
        slug: 'tokyo',
        name: 'Tokyo',
        nameCn: '东京',
        nameLocal: '東京（とうきょう）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '传统与未来交汇的世界级都市，从百年神社到摩天大楼，从米其林三星到街边拉面，东京拥有无限可能。',
        descriptionLong: '东京是一座永不停歇的城市，在这里你可以在清晨参观明治神宫感受宁静，在中午穿梭于银座的精品店，在夜晚登上东京塔俯瞰万家灯火。作为全球米其林星星最多的城市，东京是美食家的天堂；作为动漫与科技的中心，这里是二次元爱好者的圣地。\n\n东京分为 23 个特别区，每个区都有独特的魅力：新宿的繁华、涩谷的潮流、浅草的怀旧、银座的奢华、原宿的青春、秋叶原的动漫……一座城市，万种体验。',
        coverImage: IMG.tokyo,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
          'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
          'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
          'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=8xN_RBvVjCk',
        highlight: JSON.stringify([
          '🏯 浅草寺 — 东京最古老的寺庙，雷门大灯笼是东京的标志',
          '🗼 东京塔 & 晴空塔 — 360° 俯瞰整座城市的壮观',
          '🌸 新宿御苑 — 四季花卉，樱花季绝美',
          '🛍️ 银座 & 表参道 — 世界顶级购物天堂',
          '🍣 筑地场外市场 — 新鲜寿司与海鲜的圣地',
          '🎮 秋叶原 — 动漫、游戏、电器爱好者的天堂',
          '🎭 歌舞伎座 — 欣赏一场传统歌舞伎表演',
        ]),
        bestSeason: '春秋两季最佳（3-5 月樱花，10-11 月红叶），全年皆宜',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 1,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'osaka' },
      update: {
        nameCn: '大阪',
        description: '日本的美食之都与"天下厨房"，热情豪放的关西文化，道顿堀的霓虹灯与大阪城的威严交相辉映。',
        descriptionLong: '大阪是一座让人来了就不想走的城市。这里是日本公认的美食天堂——章鱼烧、大阪烧、串炸、拉面，每一道街头小吃都能让你流连忘返。当地人常说"京都人穿穷，大阪人吃穷"，足见大阪人对美食的执着。\n\n除了美食，大阪还有丰富的历史文化：大阪城是日本最宏伟的城堡之一，通天阁是新世界的标志，四天王寺是日本最古老的佛教寺庙。夜晚的道顿堀和心斋桥是购物和娱乐的天堂，而 USJ 环球影城则是家庭和年轻人的必去之地。\n\n大阪人的热情好客也是日本独特的文化体验，这里没有东京的拘谨，更多的是一种"自家"的亲切感。',
        coverImage: IMG.osaka,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&q=80',
          'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=800&q=80',
          'https://images.unsplash.com/photo-1590523734725-4843c74b209e?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🏯 大阪城 — 日本最宏伟的城堡，樱花季节绝美',
          '🍜 道顿堀 — 吃遍章鱼烧、大阪烧、串炸的美食圣地',
          '🎢 日本环球影城 USJ — 超级任天堂世界 & 哈利波特魔法世界',
          '🗼 通天阁 — 大阪新世界的标志性地标',
          '🛍️ 心斋桥 & 难波 — 购物天堂，从药妆到奢侈品应有尽有',
          '🦈 海游馆 — 世界最大级别的室内水族馆',
          '🏮 黑门市场 — "大阪的厨房"，新鲜海鲜与地道小吃',
        ]),
        bestSeason: '全年皆宜，3-4 月樱花季和 10-11 月秋季最佳',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 2,
      },
      create: {
        slug: 'osaka',
        name: 'Osaka',
        nameCn: '大阪',
        nameLocal: '大阪（おおさか）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '日本的美食之都与"天下厨房"，热情豪放的关西文化，道顿堀的霓虹灯与大阪城的威严交相辉映。',
        descriptionLong: '大阪是一座让人来了就不想走的城市。这里是日本公认的美食天堂——章鱼烧、大阪烧、串炸、拉面，每一道街头小吃都能让你流连忘返。当地人常说"京都人穿穷，大阪人吃穷"，足见大阪人对美食的执着。\n\n除了美食，大阪还有丰富的历史文化：大阪城是日本最宏伟的城堡之一，通天阁是新世界的标志，四天王寺是日本最古老的佛教寺庙。夜晚的道顿堀和心斋桥是购物和娱乐的天堂，而 USJ 环球影城则是家庭和年轻人的必去之地。\n\n大阪人的热情好客也是日本独特的文化体验，这里没有东京的拘谨，更多的是一种"自家"的亲切感。',
        coverImage: IMG.osaka,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&q=80',
          'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=800&q=80',
          'https://images.unsplash.com/photo-1590523734725-4843c74b209e?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=VJwNjHnMfEo',
        highlight: JSON.stringify([
          '🏯 大阪城 — 日本最宏伟的城堡，樱花季节绝美',
          '🍜 道顿堀 — 吃遍章鱼烧、大阪烧、串炸的美食圣地',
          '🎢 日本环球影城 USJ — 超级任天堂世界 & 哈利波特魔法世界',
          '🗼 通天阁 — 大阪新世界的标志性地标',
          '🛍️ 心斋桥 & 难波 — 购物天堂，从药妆到奢侈品应有尽有',
          '🦈 海游馆 — 世界最大级别的室内水族馆',
          '🏮 黑门市场 — "大阪的厨房"，新鲜海鲜与地道小吃',
        ]),
        bestSeason: '全年皆宜，3-4 月樱花季和 10-11 月秋季最佳',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 2,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'sapporo' },
      update: {
        nameCn: '札幌',
        description: '北海道的首府，粉雪天堂与美食之城，冬季冰雪祭举世闻名，夏季薰衣草花田美不胜收。',
        descriptionLong: '札幌是北海道的政治、经济和文化中心，也是一座四季分明的魅力城市。冬季，这里是世界顶级的滑雪和单板滑雪目的地，1972 年冬奥会曾在这里举办。著名的札幌冰雪节每年吸引 200 万游客，巨大的雪雕和冰雕装点整座城市。\n\n夏季的札幌则是另一番景象——富良野和美瑛的薰衣草花田如紫色海洋，十胜平原的广阔牧场令人心旷神怡。作为美食城市，札幌味噌拉面、成吉思汗烤羊肉、新鲜海鲜和乳制品都是不可错过的味觉盛宴。\n\n从札幌出发，可以轻松到达小樽运河、登别温泉、函馆夜景等北海道经典目的地，是探索北海道的绝佳大本营。',
        coverImage: IMG.hokkaido,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '❄️ 札幌冰雪节 — 每年 2 月，世界最大规模的冰雪盛会',
          '🍜 札幌拉面 — 味噌拉面的发源地，拉面共和国必去',
          '🌿 大通公园 — 城市中心的绿色长廊，四季活动不断',
          '🍺 札幌啤酒博物馆 — 品尝北海道限定的鲜啤',
          '🦀 二条市场 — 北海道最新鲜的海鲜，螃蟹吃到饱',
          '⛷️ 国际滑雪场 — 世界级粉雪，滑雪爱好者的天堂',
          '🚃 小樽运河 — 距离札幌 30 分钟，浪漫怀旧的水乡',
        ]),
        bestSeason: '冬季（12-2 月滑雪 + 冰雪节），夏季（6-8 月薰衣草 + 避暑）',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 3,
      },
      create: {
        slug: 'sapporo',
        name: 'Sapporo',
        nameCn: '札幌',
        nameLocal: '札幌（さっぽろ）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '北海道的首府，粉雪天堂与美食之城，冬季冰雪祭举世闻名，夏季薰衣草花田美不胜收。',
        descriptionLong: '札幌是北海道的政治、经济和文化中心，也是一座四季分明的魅力城市。冬季，这里是世界顶级的滑雪和单板滑雪目的地，1972 年冬奥会曾在这里举办。著名的札幌冰雪节每年吸引 200 万游客，巨大的雪雕和冰雕装点整座城市。\n\n夏季的札幌则是另一番景象——富良野和美瑛的薰衣草花田如紫色海洋，十胜平原的广阔牧场令人心旷神怡。作为美食城市，札幌味噌拉面、成吉思汗烤羊肉、新鲜海鲜和乳制品都是不可错过的味觉盛宴。\n\n从札幌出发，可以轻松到达小樽运河、登别温泉、函馆夜景等北海道经典目的地，是探索北海道的绝佳大本营。',
        coverImage: IMG.hokkaido,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=4pJb5F3zTzQ',
        highlight: JSON.stringify([
          '❄️ 札幌冰雪节 — 每年 2 月，世界最大规模的冰雪盛会',
          '🍜 札幌拉面 — 味噌拉面的发源地，拉面共和国必去',
          '🌿 大通公园 — 城市中心的绿色长廊，四季活动不断',
          '🍺 札幌啤酒博物馆 — 品尝北海道限定的鲜啤',
          '🦀 二条市场 — 北海道最新鲜的海鲜，螃蟹吃到饱',
          '⛷️ 国际滑雪场 — 世界级粉雪，滑雪爱好者的天堂',
          '🚃 小樽运河 — 距离札幌 30 分钟，浪漫怀旧的水乡',
        ]),
        bestSeason: '冬季（12-2 月滑雪 + 冰雪节），夏季（6-8 月薰衣草 + 避暑）',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 3,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'okinawa' },
      update: {
        nameCn: '冲绳',
        description: '日本的热带明珠，碧蓝海水、白色沙滩、琉球文化和世界级潜水，东方夏威夷名不虚传。',
        descriptionLong: '冲绳是日本最南端的县，拥有独特的琉球王国文化和亚热带气候。这里的海水透明度在日本首屈一指，庆良间诸岛被誉为"庆良间蓝"，是世界顶级的潜水和浮潜目的地。\n\n冲绳的文化深受中国和美国影响，首里城是琉球王国的象征，国际通则是美食和购物的天堂。冲绳料理融合了中日美三国风味，海鲜、苦瓜和泡盛酒是不可错过的特色。\n\n对于家庭旅行者，冲绳美丽海水族馆的鲸鲨和鬼蝠𫚉令人叹为观止；对于度假爱好者，恩纳村的海景度假村和石垣岛的离岛风光都是绝佳选择。冲绳的慢节奏生活也能让都市人彻底放松身心。',
        coverImage: IMG.okinawa,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=800&q=80',
          'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80',
          'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🐋 美丽海水族馆 — 世界最大级水族箱，近距离观赏鲸鲨',
          '🏝️ 庆良间诸岛 — "庆良间蓝"，世界级潜水与浮潜圣地',
          '🏯 首里城 — 琉球王国的象征，世界文化遗产',
          '🛍️ 国际通 — 冲绳最繁华的步行街，美食购物一站式',
          '🏖️ 古宇利岛 — 绝美海滩和心形岩，冲绳网红打卡地',
          '🎭 琉球文化 — 独特的音乐、舞蹈和工艺体验',
          '🤿 青洞潜水 — 初学者友好的蓝洞潜水体验',
        ]),
        bestSeason: '4-10 月最佳（海水温暖适合潜水），7-8 月为旺季',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 4,
      },
      create: {
        slug: 'okinawa',
        name: 'Okinawa',
        nameCn: '冲绳',
        nameLocal: '沖縄（おきなわ）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '日本的热带明珠，碧蓝海水、白色沙滩、琉球文化和世界级潜水，东方夏威夷名不虚传。',
        descriptionLong: '冲绳是日本最南端的县，拥有独特的琉球王国文化和亚热带气候。这里的海水透明度在日本首屈一指，庆良间诸岛被誉为"庆良间蓝"，是世界顶级的潜水和浮潜目的地。\n\n冲绳的文化深受中国和美国影响，首里城是琉球王国的象征，国际通则是美食和购物的天堂。冲绳料理融合了中日美三国风味，海鲜、苦瓜和泡盛酒是不可错过的特色。\n\n对于家庭旅行者，冲绳美丽海水族馆的鲸鲨和鬼蝠𫚉令人叹为观止；对于度假爱好者，恩纳村的海景度假村和石垣岛的离岛风光都是绝佳选择。冲绳的慢节奏生活也能让都市人彻底放松身心。',
        coverImage: IMG.okinawa,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=800&q=80',
          'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80',
          'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=7xMzNjR4jJk',
        highlight: JSON.stringify([
          '🐋 美丽海水族馆 — 世界最大级水族箱，近距离观赏鲸鲨',
          '🏝️ 庆良间诸岛 — "庆良间蓝"，世界级潜水与浮潜圣地',
          '🏯 首里城 — 琉球王国的象征，世界文化遗产',
          '🛍️ 国际通 — 冲绳最繁华的步行街，美食购物一站式',
          '🏖️ 古宇利岛 — 绝美海滩和心形岩，冲绳网红打卡地',
          '🎭 琉球文化 — 独特的音乐、舞蹈和工艺体验',
          '🤿 青洞潜水 — 初学者友好的蓝洞潜水体验',
        ]),
        bestSeason: '4-10 月最佳（海水温暖适合潜水），7-8 月为旺季',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 4,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'fukuoka' },
      update: {
        nameCn: '福冈',
        description: '九州门户与美食之都，屋台文化、豚骨拉面发源地，生活节奏舒缓的宜居之城。',
        descriptionLong: '福冈是日本九州地区最大的城市，也是距离亚洲大陆最近的日本主要城市。这里以豚骨拉面的发源地闻名世界，一兰拉面的总店就坐落于此。福冈的屋台（路边摊）文化是日本独一无二的体验——傍晚时分，中洲和天神地区会支起约 150 个屋台，提供烤串、关东煮、拉面和啤酒，是感受福冈烟火气的最佳方式。\n\n福冈的历史同样精彩：太宰府天满宫是日本最重要的天神社，福冈城遗址见证了几百年的风云变幻，博多区的运河城则是现代购物娱乐的地标。作为九州交通枢纽，从福冈出发可以轻松到达由布院温泉、阿苏火山、长崎等九州经典目的地。\n\n福冈人热情友好，生活节奏比东京大阪慢很多，是一座适合"慢旅行"的城市。物价也相对亲民，性价比极高。',
        coverImage: 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=800&q=80',
          'https://images.unsplash.com/photo-1590523734725-4843c74b209e?w=800&q=80',
          'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🍜 一兰拉面总店 — 豚骨拉面的圣地，24 小时营业',
          '🏮 中洲屋台 — 日本最大规模的路边摊文化体验',
          '⛩️ 太宰府天满宫 — 菅原道真公的神社，祈求学业灵验',
          '🏯 福冈城遗址 & 大濠公园 — 历史与自然的完美结合',
          '🛍️ 博多运河城 — 九州最大的综合购物娱乐中心',
          '♨️ 由布院温泉 — 从福冈出发 2 小时，九州最热门温泉乡',
          '🌶️ 博多明太子 — 福冈必买的特产美食',
        ]),
        bestSeason: '全年皆宜，春季樱花和秋季红叶最佳，冬季可品尝新鲜河豚',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 5,
      },
      create: {
        slug: 'fukuoka',
        name: 'Fukuoka',
        nameCn: '福冈',
        nameLocal: '福岡（ふくおか）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '九州门户与美食之都，屋台文化、豚骨拉面发源地，生活节奏舒缓的宜居之城。',
        descriptionLong: '福冈是日本九州地区最大的城市，也是距离亚洲大陆最近的日本主要城市。这里以豚骨拉面的发源地闻名世界，一兰拉面的总店就坐落于此。福冈的屋台（路边摊）文化是日本独一无二的体验——傍晚时分，中洲和天神地区会支起约 150 个屋台，提供烤串、关东煮、拉面和啤酒，是感受福冈烟火气的最佳方式。\n\n福冈的历史同样精彩：太宰府天满宫是日本最重要的天神社，福冈城遗址见证了几百年的风云变幻，博多区的运河城则是现代购物娱乐的地标。作为九州交通枢纽，从福冈出发可以轻松到达由布院温泉、阿苏火山、长崎等九州经典目的地。\n\n福冈人热情友好，生活节奏比东京大阪慢很多，是一座适合"慢旅行"的城市。物价也相对亲民，性价比极高。',
        coverImage: 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=800&q=80',
          'https://images.unsplash.com/photo-1590523734725-4843c74b209e?w=800&q=80',
          'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=5xMzNjR4jJk',
        highlight: JSON.stringify([
          '🍜 一兰拉面总店 — 豚骨拉面的圣地，24 小时营业',
          '🏮 中洲屋台 — 日本最大规模的路边摊文化体验',
          '⛩️ 太宰府天满宫 — 菅原道真公的神社，祈求学业灵验',
          '🏯 福冈城遗址 & 大濠公园 — 历史与自然的完美结合',
          '🛍️ 博多运河城 — 九州最大的综合购物娱乐中心',
          '♨️ 由布院温泉 — 从福冈出发 2 小时，九州最热门温泉乡',
          '🌶️ 博多明太子 — 福冈必买的特产美食',
        ]),
        bestSeason: '全年皆宜，春季樱花和秋季红叶最佳，冬季可品尝新鲜河豚',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 5,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'nagoya' },
      update: {
        nameCn: '名古屋',
        description: '日本制造业之都，名古屋城与战国风云，鳗鱼饭三吃的极致味觉体验，通往中部山岳的门户。',
        descriptionLong: '名古屋是日本第四大城市，也是爱知县的首府。作为丰田汽车的总部所在地，这里是日本制造业的心脏。但名古屋的魅力远不止于此——它深厚的战国历史、独特的美食文化和绝佳的地理位置使其成为中部地区的旅行枢纽。\n\n名古屋城是织田信长和丰臣秀吉时代的历史见证，天守阁上的金𩾇是名古屋的标志。德川美术馆收藏了大量德川家康相关的珍贵文物。热田神宫是日本最古老和最重要的神社之一，据传供奉着三神器之一的草薙剑。\n\n名古屋的美食同样不容错过：鳗鱼饭三吃（ひつまぶし）、味噌猪排（みそかつ）、手羽先（炸鸡翅）是名古屋三大名物。从名古屋出发，可以轻松到达高山古街、白川乡合掌村、立山黑部阿尔卑斯山脉路线等中部经典目的地。',
        coverImage: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
          'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🏯 名古屋城 — 战国风云的见证，金𩾇是城市标志',
          '🍱 鳗鱼饭三吃 — 名古屋最具代表性的美食体验',
          '⛩️ 热田神宫 — 日本最古老的神社之一，千年参天大树',
          '🚗 丰田产业技术纪念馆 — 汽车工业迷的圣地',
          '🏔️ 立山黑部 — 从名古屋出发，日本阿尔卑斯雪山走廊',
          '🏘️ 高山 & 白川乡 — 江户风情古街与世界遗产合掌村',
          '🍗 手羽先 — 名古屋风味炸鸡翅，配啤酒绝配',
        ]),
        bestSeason: '全年皆宜，4-5 月和 10-11 月最佳，冬季可前往立山黑部赏雪墙',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 6,
      },
      create: {
        slug: 'nagoya',
        name: 'Nagoya',
        nameCn: '名古屋',
        nameLocal: '名古屋（なごや）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '日本制造业之都，名古屋城与战国风云，鳗鱼饭三吃的极致味觉体验，通往中部山岳的门户。',
        descriptionLong: '名古屋是日本第四大城市，也是爱知县的首府。作为丰田汽车的总部所在地，这里是日本制造业的心脏。但名古屋的魅力远不止于此——它深厚的战国历史、独特的美食文化和绝佳的地理位置使其成为中部地区的旅行枢纽。\n\n名古屋城是织田信长和丰臣秀吉时代的历史见证，天守阁上的金𩾇是名古屋的标志。德川美术馆收藏了大量德川家康相关的珍贵文物。热田神宫是日本最古老和最重要的神社之一，据传供奉着三神器之一的草薙剑。\n\n名古屋的美食同样不容错过：鳗鱼饭三吃（ひつまぶし）、味噌猪排（みそかつ）、手羽先（炸鸡翅）是名古屋三大名物。从名古屋出发，可以轻松到达高山古街、白川乡合掌村、立山黑部阿尔卑斯山脉路线等中部经典目的地。',
        coverImage: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
          'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=6xMzNjR4jJk',
        highlight: JSON.stringify([
          '🏯 名古屋城 — 战国风云的见证，金𩾇是城市标志',
          '🍱 鳗鱼饭三吃 — 名古屋最具代表性的美食体验',
          '⛩️ 热田神宫 — 日本最古老的神社之一，千年参天大树',
          '🚗 丰田产业技术纪念馆 — 汽车工业迷的圣地',
          '🏔️ 立山黑部 — 从名古屋出发，日本阿尔卑斯雪山走廊',
          '🏘️ 高山 & 白川乡 — 江户风情古街与世界遗产合掌村',
          '🍗 手羽先 — 名古屋风味炸鸡翅，配啤酒绝配',
        ]),
        bestSeason: '全年皆宜，4-5 月和 10-11 月最佳，冬季可前往立山黑部赏雪墙',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 6,
      },
    }),
    prisma.destination.upsert({
      where: { slug: 'shikoku' },
      update: {
        nameCn: '四国',
        description: '日本最小众的秘境之地，四国八十八所巡礼、祖谷溪秘境、鸣门漩涡与濑户内海艺术祭。',
        descriptionLong: '四国是日本四大岛中最小、也是游客最少的一座，正因如此，它保留了最原生态的日本风情。这里没有拥挤的人群和商业化的喧嚣，只有壮丽的自然景观和深厚的人文底蕴。\n\n四国最著名的文化体验是"四国八十八所巡礼"——环绕四国遍访 88 座与弘法大师空海相关的寺庙，全程约 1200 公里。你可以选择全程徒步、分段体验，或者乘坐巴士完成精华路段。这是一次身心灵皆被洗涤的旅程。\n\n自然景观方面，祖谷溪的"蔓桥"是日本三大奇桥之一，鸣门海峡的漩涡是世界三大漩涡之一，小豆岛的橄榄园和二十四只眼睛映画村充满文艺气息。每三年举办一次的濑户内国际艺术祭（直岛、丰岛、犬岛等）更是将艺术与海岛完美融合，成为全球艺术爱好者的朝圣之地。\n\n四国的 seafood 也是一绝——赞岐乌冬面（香川县）、鲷鱼饭（爱媛县）、阿波尾鸡（德岛县）都是日本全国知名的美食。',
        coverImage: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
          'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800&q=80',
        ]),
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        highlight: JSON.stringify([
          '🛕 四国八十八所巡礼 — 千年朝圣之路，心灵净化之旅',
          '🌊 鸣门漩涡 — 世界三大漩涡之一，乘船近距离体验',
          '🌉 祖谷溪蔓桥 — 日本三大奇桥，深山秘境中的藤蔓桥',
          '🎨 濑户内国际艺术祭 — 直岛草间弥生南瓜、丰岛美术馆',
          '🍜 赞岐乌冬面 — 香川县名物，日本最好吃的乌冬面',
          '🫒 小豆岛 — 橄榄园、天使散步道、二十四只眼睛映画村',
          '♨️ 道后温泉 — 日本最古老的温泉之一，千与千寻灵感来源',
        ]),
        bestSeason: '春季（3-5 月樱花 + 艺术祭），秋季（10-11 月红叶 + 温泉），避开盛夏台风季',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 7,
      },
      create: {
        slug: 'shikoku',
        name: 'Shikoku',
        nameCn: '四国',
        nameLocal: '四国（しこく）',
        continent: 'Asia',
        region: '东亚',
        countryCode: 'JP',
        description: '日本最小众的秘境之地，四国八十八所巡礼、祖谷溪秘境、鸣门漩涡与濑户内海艺术祭。',
        descriptionLong: '四国是日本四大岛中最小、也是游客最少的一座，正因如此，它保留了最原生态的日本风情。这里没有拥挤的人群和商业化的喧嚣，只有壮丽的自然景观和深厚的人文底蕴。\n\n四国最著名的文化体验是"四国八十八所巡礼"——环绕四国遍访 88 座与弘法大师空海相关的寺庙，全程约 1200 公里。你可以选择全程徒步、分段体验，或者乘坐巴士完成精华路段。这是一次身心灵皆被洗涤的旅程。\n\n自然景观方面，祖谷溪的"蔓桥"是日本三大奇桥之一，鸣门海峡的漩涡是世界三大漩涡之一，小豆岛的橄榄园和二十四只眼睛映画村充满文艺气息。每三年举办一次的濑户内国际艺术祭（直岛、丰岛、犬岛等）更是将艺术与海岛完美融合，成为全球艺术爱好者的朝圣之地。\n\n四国的 seafood 也是一绝——赞岐乌冬面（香川县）、鲷鱼饭（爱媛县）、阿波尾鸡（德岛县）都是日本全国知名的美食。',
        coverImage: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
          'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800&q=80',
        ]),
        videoUrl: 'https://www.youtube.com/watch?v=7xMzNjR4jJk',
        highlight: JSON.stringify([
          '🛕 四国八十八所巡礼 — 千年朝圣之路，心灵净化之旅',
          '🌊 鸣门漩涡 — 世界三大漩涡之一，乘船近距离体验',
          '🌉 祖谷溪蔓桥 — 日本三大奇桥，深山秘境中的藤蔓桥',
          '🎨 濑户内国际艺术祭 — 直岛草间弥生南瓜、丰岛美术馆',
          '🍜 赞岐乌冬面 — 香川县名物，日本最好吃的乌冬面',
          '🫒 小豆岛 — 橄榄园、天使散步道、二十四只眼睛映画村',
          '♨️ 道后温泉 — 日本最古老的温泉之一，千与千寻灵感来源',
        ]),
        bestSeason: '春季（3-5 月樱花 + 艺术祭），秋季（10-11 月红叶 + 温泉），避开盛夏台风季',
        currency: '日元 (JPY)',
        language: '日语',
        timezone: 'UTC+9',
        isFeatured: true,
        sortOrder: 7,
      },
    }),
  ]);

  console.log('✅ 目的地数据已创建');

  // 3. 创建行程（覆盖 7 大目的地）
  const trips = await Promise.all([
    prisma.trip.upsert({
      where: { slug: 'japan-zen-journey' },
      update: {},
      create: {
        slug: 'japan-zen-journey',
        title: 'Zen Journey Through Japan',
        titleCn: '日本禅意之旅',
        subtitle: '从东京到京都，感受日本文化的精髓',
        tagline: '在喧嚣中寻找宁静，在古老中感受现代',
        description: '一段深度探索日本文化的旅程，从现代化的东京到千年古都京都，体验传统与现代的完美融合。沿途拜访古寺名刹，体验茶道花道，在温泉乡中放松身心，感受日本"侘寂"之美。',
        coverImage: IMG.japanZen,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
          'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
        ]),
        duration: 10,
        nights: 9,
        minGuests: 2,
        difficulty: 'Easy',
        activityLevel: 'Relaxed',
        emotionId: emotions[0].id,
        categories: JSON.stringify(['Cultural', 'Wellness', 'Heritage']),
        experiences: JSON.stringify(['Temple Visit', 'Tea Ceremony', 'Onsen', 'Zen Meditation']),
        destinationId: destinations[0].id,
        subDestinations: JSON.stringify(['东京', '箱根', '京都', '奈良']),
        priceFrom: 38000,
        priceCurrency: 'CNY',
        priceNote: '每人价格，基于 2 人出行',
        isInquireOnly: true,
        isFeatured: true,
        isExclusive: true,
        sortOrder: 1,
                inclusions: '[]',
        exclusions: '[]',
        packingList: '[]',
        isActive: true,
      },
    }),
    prisma.trip.upsert({
      where: { slug: 'japan-sakura-season' },
      update: {},
      create: {
        slug: 'japan-sakura-season',
        title: 'Cherry Blossom Season',
        titleCn: '樱花季限定之旅',
        subtitle: '追逐日本最美的樱花季',
        tagline: '在樱花飞舞的季节，遇见最美的日本',
        description: '专为樱花季设计的限定行程，带您走遍日本最美的赏樱胜地。从东京的上野公园到京都的哲学之道，在大阪城下野餐，在奈良公园与鹿共赏樱花。每一站都是专属的粉色回忆。',
        coverImage: IMG.japanSakura,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
          'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800&q=80',
        ]),
        duration: 7,
        nights: 6,
        minGuests: 2,
        difficulty: 'Easy',
        activityLevel: 'Relaxed',
        emotionId: emotions[2].id,
        categories: JSON.stringify(['Cultural', 'Nature', 'Photography']),
        experiences: JSON.stringify(['Hanami', 'Garden Visit', 'Photography', 'Kimono Experience']),
        destinationId: destinations[1].id,
        subDestinations: JSON.stringify(['东京', '京都', '大阪']),
        priceFrom: 32000,
        priceCurrency: 'CNY',
        priceNote: '每人价格，基于 2 人出行',
        isInquireOnly: true,
        isFeatured: true,
        isExclusive: true,
        sortOrder: 2,
                inclusions: '[]',
        exclusions: '[]',
        packingList: '[]',
        isActive: true,
      },
    }),
    prisma.trip.upsert({
      where: { slug: 'japan-onsen-wellness' },
      update: {},
      create: {
        slug: 'japan-onsen-wellness',
        title: 'Onsen & Wellness Retreat',
        titleCn: '温泉养生之旅',
        subtitle: '在日本温泉乡中放松身心',
        tagline: '让温泉治愈身心，让时光慢下来',
        description: '一段专注于放松和养生的旅程，体验日本最顶级的温泉文化。从北海道的登别温泉到九州的由布院温泉，每一处都是远离尘嚣的世外桃源。搭配怀石料理和冥想体验，让身心焕然一新。',
        coverImage: IMG.japanOnsen,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
        ]),
        duration: 8,
        nights: 7,
        minGuests: 2,
        difficulty: 'Easy',
        activityLevel: 'Relaxed',
        emotionId: emotions[1].id,
        categories: JSON.stringify(['Wellness', 'Luxury', 'Culinary']),
        experiences: JSON.stringify(['Onsen', 'Spa', 'Meditation', 'Kaiseki Dining']),
        destinationId: destinations[2].id,
        subDestinations: JSON.stringify(['札幌', '登别', '箱根', '由布院']),
        priceFrom: 45000,
        priceCurrency: 'CNY',
        priceNote: '每人价格，基于 2 人出行',
        isInquireOnly: true,
        isFeatured: true,
        isExclusive: false,
        sortOrder: 3,
                inclusions: '[]',
        exclusions: '[]',
        packingList: '[]',
        isActive: true,
      },
    }),
    prisma.trip.upsert({
      where: { slug: 'okinawa-island-paradise' },
      update: {},
      create: {
        slug: 'okinawa-island-paradise',
        title: 'Okinawa Island Paradise',
        titleCn: '冲绳海岛度假之旅',
        subtitle: '碧海蓝天，琉球风情的热带天堂',
        tagline: '在东方的夏威夷，享受最纯粹的度假时光',
        description: '冲绳拥有日本最美的海水和最慢的节奏。在庆良间诸岛浮潜，在美丽海水族馆与鲸鲨共舞，在国际通品尝冲绳料理，在古宇利岛的海滩上迎接日落。这是一次完全放松身心的海岛之旅。',
        coverImage: IMG.okinawa,
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=800&q=80',
          'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80',
        ]),
        duration: 5,
        nights: 4,
        minGuests: 2,
        difficulty: 'Easy',
        activityLevel: 'Relaxed',
        emotionId: emotions[2].id,
        categories: JSON.stringify(['Beach', 'Wellness', 'Family']),
        experiences: JSON.stringify(['Snorkeling', 'Aquarium', 'Beach Resort', 'Ryukyu Culture']),
        destinationId: destinations[3].id,
        subDestinations: JSON.stringify(['那霸', '恩纳村', '庆良间诸岛', '古宇利岛']),
        priceFrom: 18000,
        priceCurrency: 'CNY',
        priceNote: '每人价格，基于 2 人出行',
        isInquireOnly: true,
        isFeatured: true,
        isExclusive: false,
        sortOrder: 4,
                inclusions: '[]',
        exclusions: '[]',
        packingList: '[]',
        isActive: true,
      },
    }),
    prisma.trip.upsert({
      where: { slug: 'shikoku-hidden-gems' },
      update: {},
      create: {
        slug: 'shikoku-hidden-gems',
        title: 'Shikoku Hidden Gems',
        titleCn: '四国秘境探索之旅',
        subtitle: '日本最小众的秘境之地',
        tagline: '远离人群，发现最真实的日本',
        description: '四国是日本游客最少却最值得一去的地方。走过千年朝圣之路四国八十八所，在祖谷溪的蔓桥上感受惊险，在鸣门海峡观赏世界三大漩涡，在濑户内海的艺术岛屿上感受当代艺术的魅力。这是一次不走寻常路的深度探索。',
        coverImage: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80',
        gallery: JSON.stringify([
          'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
          'https://images.unsplash.com/photo-1490807826664-38f207026c9d?w=800&q=80',
        ]),
        duration: 6,
        nights: 5,
        minGuests: 2,
        difficulty: 'Moderate',
        activityLevel: 'Active',
        emotionId: emotions[4].id,
        categories: JSON.stringify(['Adventure', 'Cultural', 'Art']),
        experiences: JSON.stringify(['Pilgrimage', 'Art Island', 'Nature Walk', 'Udon Making']),
        destinationId: destinations[6].id,
        subDestinations: JSON.stringify(['德岛', '高知', '松山', '直岛', '丰岛']),
        priceFrom: 28000,
        priceCurrency: 'CNY',
        priceNote: '每人价格，基于 2 人出行',
        isInquireOnly: true,
        isFeatured: true,
        isExclusive: true,
        sortOrder: 5,
                inclusions: '[]',
        exclusions: '[]',
        packingList: '[]',
        isActive: true,
      },
    }),
  ]);

  console.log('✅ 行程数据已创建');

  // 4. 创建旅行专家
  const experts = await Promise.all([
    prisma.travelExpert.upsert({
      where: { slug: 'sarah-chen' },
      update: {},
      create: {
        slug: 'sarah-chen',
        name: 'Sarah Chen',
        title: '资深日本旅行专家',
        avatar: IMG.expert1,
        bio: '在日本生活 15 年，精通日本文化和语言。擅长为客户设计深度文化体验行程。',
        specialties: JSON.stringify(['日本文化', '茶道', '京都深度游']),
        languages: JSON.stringify(['中文', '日语', '英语']),
        yearsExperience: 15,
        quote: '真正的旅行，是用心去感受每一个瞬间',
        isAvailable: true,
        sortOrder: 1,
      },
    }),
    prisma.travelExpert.upsert({
      where: { slug: 'marco-rossi' },
      update: {},
      create: {
        slug: 'marco-rossi',
        name: 'Marco Rossi',
        title: '日本美食与葡萄酒专家',
        avatar: IMG.expert2,
        bio: '意大利出身，在日本钻研美食文化 10 年。擅长为客户设计美食主题行程。',
        specialties: JSON.stringify(['日本料理', '清酒品鉴', '美食之旅']),
        languages: JSON.stringify(['英语', '日语', '意大利语']),
        yearsExperience: 10,
        quote: '美食是了解一个文化最好的方式',
        isAvailable: true,
        sortOrder: 2,
      },
    }),
    prisma.travelExpert.upsert({
      where: { slug: 'yuki-tanaka' },
      update: {},
      create: {
        slug: 'yuki-tanaka',
        name: 'Yuki Tanaka',
        title: '日本自然与户外专家',
        avatar: IMG.expert3,
        bio: '日本本地人，热爱自然和户外活动。擅长为客户设计户外探险行程。',
        specialties: JSON.stringify(['富士山登山', '北海道自然', '户外探险']),
        languages: JSON.stringify(['日语', '英语']),
        yearsExperience: 8,
        quote: '大自然是最好的治愈师',
        isAvailable: true,
        sortOrder: 3,
      },
    }),
  ]);

  console.log('✅ 旅行专家数据已创建');

  // 5. 创建评价
  await Promise.all([
    prisma.review.upsert({
      where: { id: 'review-1' },
      update: {},
      create: {
        id: 'review-1',
        customerName: '王女士',
        location: '上海',
        rating: 5,
        title: '一生难忘的日本之旅',
        content: '这次日本之旅完全超出了我的期待。Sarah 为我们设计的行程非常贴心，每一个环节都安排得恰到好处。在京都的和服体验和茶道课程是最难忘的部分。强烈推荐！',
        tripId: trips[0].id,
        tripDate: new Date('2026-03-15'),
        isVerified: true,
        isFeatured: true,
        isActive: true,
      },
    }),
    prisma.review.upsert({
      where: { id: 'review-2' },
      update: {},
      create: {
        id: 'review-2',
        customerName: '张先生',
        location: '北京',
        rating: 5,
        title: '完美的樱花季体验',
        content: '樱花季的日本真的太美了！苹果旅行的团队帮我们安排了最好的赏樱地点，避开人群，享受独属于我们的樱花时光。温泉酒店的选择也非常棒。',
        tripId: trips[1].id,
        tripDate: new Date('2026-04-05'),
        isVerified: true,
        isFeatured: true,
        isActive: true,
      },
    }),
  ]);

  console.log('✅ 评价数据已创建');

  // 6. 创建文章
  await Promise.all([
    prisma.article.create({
      data: {
        slug: 'why-emotion-travel-matters',
        type: 'STORY',
        title: '为什么情感旅行比目的地更重要？',
        subtitle: '从 APPLE TRAVEL 的 Feelings Engine 说起',
        coverImage: IMG.story1,
        content: '<p>在旅行行业 20 年，我们发现了一个有趣的现象：人们回来后记得的不是去了哪里，而是感受到了什么。这正是我们推出情感选择器的原因...</p>',
        author: 'Sarah Chen',
        readTime: 5,
                gallery: '[]',
        categories: '[]',
        tags: '[]',
        isFeatured: true,
        isPublished: true,
        publishedAt: new Date('2026-05-01'),
      },
    }),
    prisma.article.create({
      data: {
        slug: 'best-time-visit-japan',
        type: 'GUIDE',
        title: '日本最佳旅行时间完全指南',
        subtitle: '春夏秋冬，各有不同的美',
        coverImage: IMG.story2,
        content: '<p>日本四季分明，每个季节都有独特的魅力。春季赏樱，夏季花火，秋季红叶，冬季粉雪。本文为您详细分析每个季节的优缺点...</p>',
        author: 'Yuki Tanaka',
        readTime: 8,
                gallery: '[]',
        categories: '[]',
        tags: '[]',
        isFeatured: true,
        isPublished: true,
        publishedAt: new Date('2026-05-15'),
      },
    }),
    prisma.article.create({
      data: {
        slug: 'japan-onsen-guide',
        type: 'FEATURE',
        title: '日本温泉完全指南：从入门到精通',
        subtitle: '从钱汤到顶级温泉旅馆，一次搞懂日本温泉文化',
        coverImage: IMG.story3,
        content: '<p>温泉是日本文化的重要组成部分。从街头的钱汤到山顶的秘汤，每一种温泉都有其独特的魅力。本文将带您深入了解日本温泉文化...</p>',
        author: 'Marco Rossi',
        readTime: 10,
                gallery: '[]',
        categories: '[]',
        tags: '[]',
        isFeatured: true,
        isPublished: true,
        publishedAt: new Date('2026-05-20'),
      },
    }),
  ]);

  console.log('✅ 文章数据已创建');

  // 7. 创建播客
  await Promise.all([
    prisma.podcast.create({
      data: {
        slug: 'episode-1-japan-culture',
        title: '日本文化深度解析：传统与现代的融合',
        description: '本期节目我们邀请 Sarah Chen 分享她在日本生活 15 年的见闻，探讨日本文化中传统与现代的奇妙融合。',
        coverImage: IMG.story1,
        audioUrl: '#',
        duration: 1800,
        episodeNumber: 1,
        seasonNumber: 1,
        guests: JSON.stringify(['Sarah Chen']),
        isPublished: true,
        publishedAt: new Date('2026-05-01'),
      },
    }),
    prisma.podcast.create({
      data: {
        slug: 'episode-2-japan-food',
        title: '日本美食地图：从街头小吃到米其林',
        description: 'Marco Rossi 带您探索日本美食的方方面面，从拉面到怀石料理，从居酒屋到米其林三星。',
        coverImage: IMG.story2,
        audioUrl: '#',
        duration: 2100,
        episodeNumber: 2,
        seasonNumber: 1,
        guests: JSON.stringify(['Marco Rossi']),
        isPublished: true,
        publishedAt: new Date('2026-05-15'),
      },
    }),
  ]);

  console.log('✅ 播客数据已创建');

  console.log('🎉 所有种子数据已创建完成！');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
